# Generated by Django 3.2.8 on 2021-11-17 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_remove_orderitem_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
