# Generated by Django 3.1.7 on 2021-10-25 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211025_1050'),
        ('specs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryfeature',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='featurevalidator',
            name='category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='featurevalidator',
            name='feature_key',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='specs.categoryfeature', verbose_name='Ключ характеристики'),
        ),
        migrations.AddField(
            model_name='productfeatures',
            name='feature',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='specs.categoryfeature', verbose_name='Характеристика'),
        ),
        migrations.AddField(
            model_name='productfeatures',
            name='product',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.product', verbose_name='Товар'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryfeature',
            unique_together={('category', 'feature_name', 'feature_filter_name')},
        ),
    ]
