# Generated by Django 3.2.8 on 2022-01-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_remove_product_features'),
        ('specs', '0002_auto_20211025_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurevalidator',
            name='category',
        ),
        migrations.RemoveField(
            model_name='featurevalidator',
            name='feature_key',
        ),
        migrations.RemoveField(
            model_name='productfeatures',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='productfeatures',
            name='product',
        ),
        migrations.DeleteModel(
            name='CategoryFeature',
        ),
        migrations.DeleteModel(
            name='FeatureValidator',
        ),
        migrations.DeleteModel(
            name='ProductFeatures',
        ),
    ]
