# Generated by Django 3.1.7 on 2021-10-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20211025_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='f_name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='account',
            name='l_name',
            field=models.CharField(default='', max_length=255, verbose_name='Фамилия'),
        ),
    ]
