# Generated by Django 3.2.8 on 2021-10-27 11:51

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20211026_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Товары', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='account',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='f_name', unique=True),
        ),
    ]
