# Generated by Django 3.2.8 on 2021-10-27 11:57

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20211027_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default='', editable=False, null=True, populate_from='f_name', unique=True),
        ),
    ]
