# Generated by Django 3.2.8 on 2021-10-27 12:20

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_account_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='f_name'),
        ),
    ]
