# Generated by Django 3.2.8 on 2021-10-28 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_usersession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
