# Generated by Django 3.2.8 on 2021-10-28 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('mainapp', '0017_delete_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session'),
        ),
    ]
