# Generated by Django 3.2.8 on 2021-11-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20211030_1115'),
        ('wishlist', '0002_auto_20211030_1115'),
        ('mainapp', '0024_auto_20211031_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products_cart',
            field=models.ManyToManyField(to='cart.OrderItem', verbose_name='Продукты в корзине'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products_wishlist',
            field=models.ManyToManyField(editable=False, to='wishlist.OrderItem', verbose_name='Продукты в желаниях'),
        ),
    ]
