# Generated by Django 3.2.8 on 2021-11-02 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20211102_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buying_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
    ]
