# Generated by Django 3.2.8 on 2021-11-03 07:59

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_auto_20211102_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(default=models.CharField(db_index=True, max_length=255, verbose_name='Наименование'), null=True),
        ),
    ]
