# Generated by Django 3.2.8 on 2021-11-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_alter_product_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='В процентах. Значок процента не ставить!', max_digits=5, verbose_name='Величина скидки'),
        ),
    ]
