# Generated by Django 3.2.8 on 2021-11-24 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_auto_20211123_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='like',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Кол-во'),
        ),
    ]
