# Generated by Django 3.2.8 on 2021-11-25 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_auto_20211124_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='quantity',
        ),
    ]
