# Generated by Django 3.2.8 on 2021-11-25 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_remove_like_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislike',
            name='is_click',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='like',
            name='is_click',
        ),
    ]
