# Generated by Django 3.2.8 on 2022-01-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0004_categoryfeature_featurevalidator_productfeatures'),
        ('mainapp', '0040_remove_product_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='features_for_product', to='specs.ProductFeatures', verbose_name='Характеристика товара'),
        ),
    ]
