# Generated by Django 3.2.8 on 2022-03-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_product_features'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='mainapp_pro_search__f82656_gin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='search_vector',
        ),
    ]
