# Generated by Django 4.1 on 2022-08-06 09:18

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
from django.contrib.postgres.search import SearchVector


def compute_search_vector(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Product.objects.update(search_vector=SearchVector("title"))


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0042_auto_20220315_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='mainapp_pro_search__f82656_gin'),
        ),
    ]
