# Generated by Django 3.2.8 on 2021-11-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_orderitem_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='get_cart_price_not_auth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Сумма'),
        ),
    ]
