# Generated by Django 3.2.8 on 2021-11-16 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_orderitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='get_cart_price_not_auth',
        ),
    ]
